---
abstract: 'Interface to Income Tax of UK.'
author:
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
build_requires:
  Readonly: 1.03
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IncomeTax-UK
provides:
  IncomeTax::UK:
    file: lib/IncomeTax/UK.pm
    version: 0.08
resources:
  license: http://dev.perl.org/licenses/
version: 0.08
